[project]
name = "anomaly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
<<<<<<< HEAD
dependencies = [
    "notebook>=7.4.5",
    "pytest>=8.4.1",
]
=======
dependencies = []
>>>>>>> 7965e9a398f730812246052e78e9aff32e177b24
